name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
         cd Tools
         ./install_dep.sh
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: output
          path: . 
